command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"
env:
  - name: GENIE_SPACE_ID
    value: "01f1b03319ec17daa40d884a21f77386"
  - name: LAKEBASE_HOST
    value: "ep-hidden-fire-e9y4qh66.database.eastus.azuredatabricks.net"
  - name: PGDATABASE
    value: "lead_opt"
  - name: WAREHOUSE_ID
    value: "13d08bfefc608fe6"
